load(
    "//tools/skylark:drake_cc.bzl",
    "drake_cc_binary",
)
load("//tools/skylark:drake_py.bzl", "drake_py_binary")

package(default_visibility = ["//visibility:public"])

drake_cc_binary(
    name = "conveyor_belt",
    srcs = ["conveyor_belt.cc"],
    data = [
        "conveyor_belt.sdf",
        "conveyor_belt_ex.sdf",
        "//examples/scene_graph:models",
    ],
    deps = [
        "//examples/lcs:options",
        "//examples/lcs:lcs_factory_system",
        "//examples/lcs:framework",
        "//geometry:meshcat_visualizer",
        "//geometry:scene_graph",
        "//multibody/meshcat:contact_visualizer",
        "//multibody/parsing",
        "//multibody/plant",
        "//systems/analysis:simulator",
        "//systems/framework:diagram",
        "//systems/framework:leaf_system",
        "//systems/primitives:sine",
        "@gflags",
    ],
)

drake_cc_binary(
    name = "conveyor_belt_gripper",
    srcs = ["conveyor_belt_gripper.cc"],
    data = [
        "conveyor_gripper_scene.sdf",
        "@drake_models//:iiwa_description",
    ],
    deps = [
        "//geometry:scene_graph_config",
        "//examples/kuka_iiwa_arm:iiwa_lcm",
        "//examples/kuka_iiwa_arm:iiwa_common",
        "//lcm:drake_lcm",
        "//multibody/plant",
        "//multibody/parsing",
        "//systems/analysis:simulator",
        "//systems/framework:diagram",
        "//visualization",
        "@gflags",
    ]
)

drake_py_binary(
    name = "conveyor_gripper",
    srcs = ["conveyor_gripper.py"],
    add_test_rule = 1,
    data = [":models"],
    test_rule_args = [
        "--target_realtime_rate=0",
        "--simulation_time=0.1",
    ],
    deps = [
        "//bindings/pydrake",
    ],
)