load(
    "//tools/skylark:drake_cc.bzl",
    "drake_cc_binary",
)

drake_cc_binary(
    name = "conveyor_belt",
    srcs = ["conveyor_belt.cc"],
    data = [
        "conveyor_belt.sdf",
        "//examples/scene_graph:models",
    ],
    deps = [
        "//geometry:meshcat_visualizer",
        "//geometry:scene_graph",
        "//multibody/meshcat:contact_visualizer",
        "//multibody/parsing",
        "//multibody/plant",
        "//systems/analysis:simulator",
        "//systems/framework:diagram",
        "//systems/framework:leaf_system",
        "@gflags",
    ],
)

drake_cc_binary(
    name = "conveyor_belt_gripper",
    srcs = ["conveyor_belt_gripper.cc"],
    data = [
        "//examples/hydroelastic/conveyor_gripper:models",
        "@drake_models//:iiwa_description",
    ],
    deps = [
        "//examples/kuka_iiwa_arm:iiwa_lcm",
        "//examples/kuka_iiwa_arm:iiwa_common",
        "//lcm:drake_lcm",
        "//multibody/plant",
        "//multibody/parsing",
        "//systems/analysis:simulator",
        "//systems/framework:diagram",
        "//visualization",
        "@gflags",
    ]
)